countries = {
    "ar": "Argentina",
    "at": "Austria",
    "au": "Australia",
    "ba": "Bosnia and Herzegovina",
    "bd": "Bangladesh",
    "be": "Belgium",
    "br": "Brazil",
    "ca": "Canada",
    "ch": "Switzerland",
    "cl": "Chile",
    "cn": "China",
    "co": "Colombia",
    "cz": "Czech Republic",
    "de": "Germany",
    "dk": "Denmark",
    "ee": "Estonia",
    "eg": "Egypt",
    "es": "Spain",
    "fi": "Finland",
    "fr": "France",
    "gb": "United Kingdom",
    "gr": "Greece",
    "hk": "Hong Kong",
    "hr": "Croatia",
    "hu": "Hungary",
    "id": "Indonesia",
    "ie": "Ireland",
    "il": "Israel",
    "in": "India",
    "iq": "Iraq",
    "is": "Iceland",
    "it": "Italy",
    "jp": "Japan",
    "kh": "Cambodia",
    "kr": "Korea, Republic of",
    "kw": "Kuwait",
    "lt": "Lithuania",
    "ma": "Morocco",
    "me": "Montenegro",
    "mk": "Republic of North Macedonia",
    "mn": "Mongolia",
    "mv": "Maldives",
    "mx": "Mexico",
    "my": "Malaysia",
    "no": "Norway",
    "pe": "Peru",
    "ph": "Philippines",
    "pl": "Poland",
    "pt": "Portugal",
    "ro": "Romania",
    "rs": "Serbia",
    "sa": "Saudi Arabia",
    "se": "Sweden",
    "sg": "Singapore",
    "si": "Slovenia",
    "th": "Thailand",
    "tr": "Turkey",
    "tw": "Taiwan, Province of China",
    "ua": "Ukraine",
    "us": "United States",
    "vn": "Viet Nam",
    "eu": "Europe",
    "un": "-",
}
